### ISSUE TITLE
Trying to install again from another computer

### ISSUE THREAD

**Issue by trololo151** [kuper-adrian/statg-bot#18]
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'pubg-royale'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (E:\statg-bot-master\statg-bot-master\src\bot.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

E:\statg-bot-master\statg-bot-master\src>

**Comment by kuper-adrian** [comment]
Did you run `npm install`?

**Comment by trololo151** [comment]
fix it. 
npm rebuild
